name: Sync to Gitee with Mirror
on:
  schedule:
    - cron: "0 16 * * *"  # 每天北京时间 0 点（UTC+8）执行，对应 UTC 时间为 16 点
  workflow_dispatch:  # 也可以手动触发
jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - { source: "ScoopInstaller/Scoop", target: "scoop_mirror/Scoop" }
          - { source: "ScoopInstaller/Main", target: "scoop_mirror/Main" }
          - { source: "ScoopInstaller/Extras", target: "scoop_mirror/Extras" }
          - { source: "ScoopInstaller/Nonportable", target: "scoop_mirror/Nonportable" }
          - { source: "ScoopInstaller/Java", target: "scoop_mirror/Java" }
    steps:
      - name: Set up Git environment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Clone source repository as mirror
        run: |
          git clone https://github.com/${{ matrix.repo.source }}.git source-repo-mirror
          cd source-repo-mirror
          git fetch --tags  # 确保获取所有标签
      - name: Push mirror to target repository
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          cd source-repo-mirror
          git remote set-url origin https://$GITEE_TOKEN@gitee.com/${{ matrix.repo.target }}.git
          # 获取所有非隐藏引用并逐一推送
          git for-each-ref --format='%(refname)' refs/heads refs/tags | grep -v 'refs/pull/' | while read ref; do
            echo "Pushing $ref"
            if ! git push origin "$ref"; then
              echo "Failed to push $ref"
              git push origin "$ref" --verbose
              exit 1
            fi
          done
      - name: Log sync status
        run: |
          echo "Sync completed successfully at $(date)"
      - name: Clean up
        run: |
          rm -rf source-repo-mirror
